
name: Build

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

  workflow_dispatch:

jobs:
    tox-job:
      name: Tox Job
      runs-on: ubuntu-latest
      steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Install req.txt
        run: |
          pip install -r requirements.txt
      
      - name: Run tox
        run: |
          tox
